force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>GameID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Creation_Time__c.field-meta.xml
<CustomField>
    <fullName>Creation_Time__c</fullName>
    <label>Creation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Map__c.field-meta.xml
<CustomField>
    <fullName>Map__c</fullName>
    <label>Map</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
                <label>Summoner&#39;s Rift</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CLASSIC</fullName>
                <label>Classic Summoner's Rift</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUW1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>420</fullName>
                <default>true</default>
                <label>5v5 Ranked Solo games</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>PRESEASON 3</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>SEASON 3</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>PRESEASON 2014</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>SEASON 2014</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PRESEASON 2015</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>SEASON 2015</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>PRESEASON 2016</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>SEASON 2016</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>PRESEASON 2017</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>SEASON 2017</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>PRESEASON 2018</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>SEASON 2018</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>PRESEASON 2019</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>SEASON 2019</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MATCHED_GAME</fullName>
                <label>Matched Game</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Match__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9.17.287.2485</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Summoner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Profile_Icon_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Icon_ID__c</fullName>
    <label>Profile Icon ID</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Summoner_ID__c.field-meta.xml
<CustomField>
    <fullName>Summoner_ID__c</fullName>
    <label>Summoner ID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RiotMatchObjectParser.cls
public with sharing class RiotMatchObjectParser {

private RiotJSON Match;

    public RiotMatchObjectParser(RiotJSON Match) {
        this.Match = Match;
    }

    public void initsObject(){
        createMatch();
        createPlayer();
        createParticipant();
        createTeam();
    }

    public Match__c createMatch(){
        Match__c riotMatch =  new Match__c(Name = Match.gameId.toString());
        
        riotMatch.Creation_Time__c = Match.gameCreation;
        riotMatch.Durcation__c = Match.gameDuration;
        riotMatch.Map__c = Match.mapId;
        riotMatch.Mode__c = Match.gameMode;
        riotMatch.Platform__c = Match.platformId;
        riotMatch.Queue__c = Match.queueId;
        riotMatch.Season__c = Match.seasonId;
        riotMatch.Type__c = Match.gameType;
        riotMatch.Version__c = Match.gameVersion;
    }

    public void createPlayer(){
        List<Player__c> playerList = new List<Player__c>();
        for (Match.ParticipantIdentities idPlayer : Match.participantIdentities) {
            Player__c riotPlayer = new Player__c(Name = idPlayer.player.summonerName);
            riotPlayer.Account_ID__c = idPlayer.player.accountId;
            riotPlayer.Platform__c = idPlayer.player.platformId;
            riotPlayer.Profile_Icon_ID__c = idPlayer.player.profileIcon;
            riotPlayer.Summoner_ID__c = idPlayer.player.summonerId;
            playerList.add(riotPlayer);
        }
    }

    public void createParticipant(){

    }

    public void createTeam(){

    }

    public void createChampion(){

    }
}